### ISSUE TITLE
App is crashing instantly

### ISSUE THREAD

**Issue by langebo** [devdennysegura/flutter-auth0#2]
Followed you instructions (which are kinda lacking to be honest), looked at the sample to actually find the files you mentioned and did everything you described there but when actually trying WebAuth PKCE i get the following error:;

`W/ActivityThread( 7705): handleWindowVisibility: no activity for token android.os.BinderProxy@74aad5c
D/AndroidRuntime( 7705): Shutting down VM
E/AndroidRuntime( 7705): FATAL EXCEPTION: main
E/AndroidRuntime( 7705): Process: com.blangr.fairpay, PID: 7705
E/AndroidRuntime( 7705): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.blangr.fairpay/com.blangr.fairpay.RedirectUriReceiver}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7705): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
E/AndroidRuntime( 7705): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime( 7705): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime( 7705): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 7705): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 7705): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime( 7705): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7705): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 7705): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 7705): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7705): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 7705): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 7705): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7705): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime( 7705): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:203)
E/AndroidRuntime( 7705): 	at io.flutter.plugins.flutterauth0.FlutterAuth0Plugin.resolveWebAuthentication(FlutterAuth0Plugin.java:91)
E/AndroidRuntime( 7705): 	at com.blangr.fairpay.RedirectUriReceiver.onCreate(RedirectUriReceiver.java:18)
E/AndroidRuntime( 7705): 	at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime( 7705): 	at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime( 7705): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime( 7705): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/AndroidRuntime( 7705): 	... 11 more`

**Comment by devdennysegura** [comment]
Hey @langebo , can you show me your android folder(structure) and androidmanifest.xml?
