### ISSUE TITLE
Crash android app when error occurred

### ISSUE THREAD

**Issue by imanng** [devdennysegura/flutter-auth0#40]
Android log:
```D/FlutterView(31625): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@a8b6709
W/ActivityThread(31625): handleWindowVisibility: no activity for token android.os.BinderProxy@3df2479
D/AndroidRuntime(31625): Shutting down VM
E/AndroidRuntime(31625): FATAL EXCEPTION: main
E/AndroidRuntime(31625): Process: com.xxx.xxxxx, PID: 31625
E/AndroidRuntime(31625): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxxxx/io.flutter.plugins.flutterauth0.AuthenticationReceiver}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31625): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2952)
E/AndroidRuntime(31625): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
E/AndroidRuntime(31625): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(31625): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(31625): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(31625): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
E/AndroidRuntime(31625): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31625): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(31625): 	at android.app.ActivityThread.main(ActivityThread.java:6746)
E/AndroidRuntime(31625): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31625): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(31625): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(31625): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31625): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/AndroidRuntime(31625): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/AndroidRuntime(31625): 	at io.flutter.plugins.flutterauth0.FlutterAuth0Plugin.resolve(FlutterAuth0Plugin.java:79)
E/AndroidRuntime(31625): 	at io.flutter.plugins.flutterauth0.AuthenticationReceiver.closeView(AuthenticationReceiver.java:35)
E/AndroidRuntime(31625): 	at io.flutter.plugins.flutterauth0.AuthenticationReceiver.onCreate(AuthenticationReceiver.java:22)
E/AndroidRuntime(31625): 	at android.app.Activity.performCreate(Activity.java:7144)
E/AndroidRuntime(31625): 	at android.app.Activity.performCreate(Activity.java:7135)
E/AndroidRuntime(31625): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
E/AndroidRuntime(31625): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
E/AndroidRuntime(31625): 	... 11 more
I/Process (31625): Sending signal. PID: 31625 SIG: 9
Lost connection to device.
```

**Comment by hoc081098** [comment]
Please see PR #41

**Comment by 1pavanb** [comment]
@hoc081098 PR #41 works for me, although it seems like the error is not printed/ masked.
Since it doesn't crash the app, it works for me.
Thank you

**Comment by 1pavanb** [comment]
> Please see PR #41

@hoc081098 PR #41 works for me, although it seems like the error is not printed/ masked.
Since it doesn't crash the app, it works for me.
Thank you

But it is not yet approved by the owner :(

**Comment by hoc081098** [comment]
@1pavanb  still waiting last approval
