### ISSUE TITLE
Auth0 login issue

### ISSUE THREAD

**Issue by rohitattaluri** [devdennysegura/flutter-auth0#46]
https://github.com/devdennysegura/flutter-auth0/blob/cf9420653208ceb56ebe61c0ab78c8f346c81e1f/example/lib/pkce.dart#L32

in the above mentioned position, I'm getting some error and not able to open auth0 authentication page in any of my browsers.

I checked only for android device.

> D/FlutterView(24900): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@90557e4
W/ActivityThread(24900): handleWindowVisibility: no activity for token android.os.BinderProxy@6995768
D/FlutterView(24900): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@90557e4
I/flutter (24900): Error: ======================>>>>>>
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
I/flutter (24900):
E/flutter (24900): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Connection closed before full header was received
E/flutter (24900): #0      IOClient.send 
package:http/src/io_client.dart:65
E/flutter (24900): <asynchronous suspension>
E/flutter (24900): #1      BaseClient._sendUnstreamed 
package:http/src/base_client.dart:176
E/flutter (24900): #2      BaseClient.patch 
package:http/src/base_client.dart:104
E/flutter (24900): #3      Auth0Client.request 
package:flutter_auth0/…/networking/client.dart:70
E/flutter (24900): #4      _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:45:6)
E/flutter (24900): #5      Auth0Client.request 
package:flutter_auth0/…/networking/client.dart:56
E/flutter (24900): #6      Auth0Client.mutate 
package:flutter_auth0/…/networking/client.dart:30
E/flutter (24900): #7      _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:45:6)
E/flutter (24900): #8      Auth0Client.mutate 
package:flutter_auth0/…/networking/client.dart:29
E/flutter (24900): #9      Auth0Auth.exchange 
package:flutter_auth0/…/auth/index.dart:99
E/flutter (24900): #10     _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:45:6)
E/flutter (24900): #11     Auth0Auth.exchange 
package:flutter_auth0/…/auth/index.dart:87
E/flutter (24900): #12     WebAuth.authorize.<anonymous closure>.<anonymous closure> 
package:flutter_auth0/…/webauth/index.dart:63
E/flutter (24900): #13     _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:45:6)
E/flutter (24900): #14     WebAuth.authorize.<anonymous closure>.<anonymous closure> 
package:flutter_auth0/…/webauth/index.dart:62
E/flutter (24900): #15     _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter (24900): #16     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)

**Comment by mkolbusz** [comment]
@rohitattaluri Do you have any parameters inside curly braces? I mean you have code like this:
```
var response = await auth.webAuth.authorize({})
```
or this 
```
var response = await auth.webAuth.authorize({'key1': 'value1', 'key2': 'value2'})
```

**Comment by rohitattaluri** [comment]
@mkolbusz  sorry dude, I forgot to close this. Actually I found some issues from my end and got fixed long back. 

Thanks for taking time for looking into this. 

I'm closing it now.

**Comment by mkolbusz** [comment]
@rohitattaluri I am glad you have resolved your problems. Could you share your code? I have still some problems and can not make Apple Sign In with auth0 works :/ Thanks for your help in advance!

**Comment by rohitattaluri** [comment]
@mkolbusz  sorry for that pal!! 

I've switched to new organization. I don't have the access for the worked codebase to get that here. 😞😞

Mostly here I got few issues with the typecasting in dart language. Due to that I failed to make AuthO work properly. Later it got fixed just like that 🤔
